services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - NODE_LOCAL_PORT=${NODE_LOCAL_PORT}
      - NODE_DOCKER_PORT=${NODE_DOCKER_PORT}
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules